//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalturBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string ArticleContent { get; set; }
        public string ArticleDate { get; set; }
        public string ArticleTags { get; set; }
        public string ArticleCatagory { get; set; }
        public string ArticleAuthor { get; set; }
        public Nullable<bool> ArticleStatus { get; set; }
        public Nullable<int> ArticleReading { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleUrl { get; set; }
        public string HomeImageUrl { get; set; }
    }
}
