//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalturBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int Id { get; set; }
        public string AuthorName { get; set; }
        public string AuthorAbout { get; set; }
        public string AuthorImageUrl { get; set; }
        public string AuthorFacebook { get; set; }
        public string AuthorTwitter { get; set; }
        public string AuthorInstagram { get; set; }
        public string AuthorPassword { get; set; }
        public string AuthorEmail { get; set; }
        public string UserRol { get; set; }
    }
}
